name: steps_tracker
description: A battery-friendly pedometer app that tracks steps, calories, distance, and time.

version: 1.0.0+1

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    provider: ^6.0.0
    sqflite: ^2.0.0+4
    path_provider: ^2.0.2
    shared_preferences: ^2.0.6
    fl_chart: ^0.68.0
    google_sign_in: ^5.0.4
    googleapis: ^5.0.1
    pedometer: ^4.0.2
    health: 11.0.0
    flutter_localizations:
        sdk: flutter
    intl: ^0.19.0
    permission_handler: ^11.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
